// <auto-generated />
using Calculator.Class;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AppContext = Calculator.Class.AppContext;

#nullable disable

namespace Calculator.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20260210152530_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Calculator.Class.Calculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("B")
                        .HasColumnType("REAL");

                    b.Property<double>("H")
                        .HasColumnType("REAL");

                    b.Property<double>("N")
                        .HasColumnType("REAL");

                    b.Property<double>("S")
                        .HasColumnType("REAL");

                    b.Property<double>("S_sr")
                        .HasColumnType("REAL");

                    b.Property<int>("SpeakerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeakerTyp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeakerType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UH")
                        .HasColumnType("REAL");

                    b.Property<double>("USH_p")
                        .HasColumnType("REAL");

                    b.Property<double>("U_vh")
                        .HasColumnType("REAL");

                    b.Property<double>("V")
                        .HasColumnType("REAL");

                    b.Property<double>("a")
                        .HasColumnType("REAL");

                    b.Property<double>("a1")
                        .HasColumnType("REAL");

                    b.Property<double>("a2")
                        .HasColumnType("REAL");

                    b.Property<double>("a_ekv")
                        .HasColumnType("REAL");

                    b.Property<double>("b_")
                        .HasColumnType("REAL");

                    b.Property<double>("delta")
                        .HasColumnType("REAL");

                    b.Property<double>("h_")
                        .HasColumnType("REAL");

                    b.Property<double>("t_r")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("Calculator.Class.Speaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("P_01")
                        .HasColumnType("REAL");

                    b.Property<double>("P_Vt")
                        .HasColumnType("REAL");

                    b.Property<double>("SHDN_g")
                        .HasColumnType("REAL");

                    b.Property<double>("SHDN_v")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Speakers");
                });
#pragma warning restore 612, 618
        }
    }
}
